WARNING 2023-08-11 07:47:49,648 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-08-11 07:54:29,824 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-08-11 07:56:57,626 log log.py 241 log_response Not Found: /adminastrer
WARNING 2023-08-11 07:57:19,275 log log.py 241 log_response Not Found: /useradmin
WARNING 2023-08-11 07:57:38,339 log log.py 241 log_response Not Found: /admindash
WARNING 2023-08-11 07:58:30,382 log log.py 241 log_response Not Found: /useradmin
WARNING 2023-08-11 11:01:04,456 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-08-11 12:02:44,221 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-08-11 12:04:18,910 log log.py 241 log_response Not Found: /favicon.ico
WARNING 2023-08-11 12:22:49,044 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-08-11 12:48:19,944 log log.py 241 log_response Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khana\OneDrive\Desktop\security\ecommerce\customer\views.py", line 121, in dashboard
    return render(request, "customer/dashboard.html", {'swals': swals, 'sweeters': sweeters, 'panchus': panchus, 'caps': caps})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Python311\Lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 16: 'if'. Looking for one of: elif, else, endif.
WARNING 2023-08-11 15:47:58,347 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-08-11 20:19:46,549 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:20:20,025 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:20:27,483 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:20:42,542 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:21:36,959 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:22:31,453 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:23:09,166 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:23:52,848 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:24:38,990 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:24:57,854 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:27:52,042 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Users\khana\OneDrive\Desktop\security\ecommerce\customer\views.py", line 111, in login_redirect
    user = Useradmin.objects.get(username=username, password=hashed_password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
useradmin.models.Useradmin.DoesNotExist: Useradmin matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khana\OneDrive\Desktop\security\ecommerce\customer\views.py", line 141, in login_redirect
    time_difference = current_time - last_activity_time
                      ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
WARNING 2023-08-11 20:29:44,143 log log.py 241 log_response Not Found: /favicon.ico
ERROR 2023-08-11 20:29:57,651 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Users\khana\OneDrive\Desktop\security\ecommerce\customer\views.py", line 111, in login_redirect
    user = Useradmin.objects.get(username=username, password=hashed_password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
useradmin.models.Useradmin.DoesNotExist: Useradmin matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khana\OneDrive\Desktop\security\ecommerce\customer\views.py", line 143, in login_redirect
    last_activity_time = datetime.fromtimestamp(last_activity_timestamp, timezone.get_timezone(last_activity_timezone))
                                                                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\timezone.py", line 47, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'django.utils.timezone' has no attribute 'get_timezone'
ERROR 2023-08-11 20:32:02,283 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Users\khana\OneDrive\Desktop\security\ecommerce\customer\views.py", line 112, in login_redirect
    user = Useradmin.objects.get(username=username, password=hashed_password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
useradmin.models.Useradmin.DoesNotExist: Useradmin matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khana\OneDrive\Desktop\security\ecommerce\customer\views.py", line 144, in login_redirect
    last_activity_time = datetime.fromtimestamp(last_activity_timestamp, pytz.timezone(last_activity_timezone))
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pytz\__init__.py", line 168, in timezone
    raise UnknownTimeZoneError(None)
pytz.exceptions.UnknownTimeZoneError: None
ERROR 2023-08-11 20:32:41,514 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:36:42,792 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\middleware.py", line 59, in process_response
    request.session.save()
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 80, in save
    return self.create()
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 82, in save
    obj = self.create_model_instance(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\db.py", line 69, in create_model_instance
    session_data=self.encode(data),
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\contrib\sessions\backends\base.py", line 94, in encode
    return signing.dumps(
           ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
ERROR 2023-08-11 20:38:21,840 log log.py 241 log_response Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Users\khana\OneDrive\Desktop\security\ecommerce\customer\views.py", line 110, in login_redirect
    user = Useradmin.objects.get(username=username, password=hashed_password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
useradmin.models.Useradmin.DoesNotExist: Useradmin matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khana\OneDrive\Desktop\security\ecommerce\customer\views.py", line 147, in login_redirect
    if last_login_time and current_time - last_login_time > timedelta(minutes=1):
       ^^^^^^^^^^^^^^^
NameError: name 'last_login_time' is not defined
